# Generated by Django 5.1.6 on 2025-05-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_branch_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_by',
        ),
    ]
