# Generated by Django 5.1.6 on 2025-05-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_branch_created_by_remove_branch_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
